name: Deploy to VPS

on:
  push:
    branches:
      - main

concurrency:
  group: deploy-main
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy
        run: /root/Telegram-bot/deploy.sh
